name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been marked as stale. Due to lack of activity.'
          stale-pr-message: 'This PR has been marked as stale. Due to lack of activity.'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
